// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplyController from "./apply_controller"
application.register("apply", ApplyController)

import CheckController from "./check_controller"
application.register("check", CheckController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SelectController from "./select_controller"
application.register("select", SelectController)
